name: SpeShow Site
url: http://www.sprabbit.com
encoding: utf-8
markdown: redcarpet
pygments: true
port: 8081
encoding: utf-8
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"